[dropbox]
APP_KEY = "dec5zj63pkh1clf"
APP_SECRET = "kj5pj8gxglmmvac"
DROPBOX_TOKEN = "46lORlRMBvMAAAAAAAAAAaVc_aUcw94mYpGE9fSScdbX1kPTVlTcQL6_3JLproXd"

[paths]
CLIENTS_FILE = "/Apps/berenbaum-law/Clients.xlsx"
ESCROW_FILE = "/Apps/berenbaum-law/Escrow.xlsx"
VISA_FILE = "/Apps/berenbaum-law/Visa.xlsx"
COMPTA_FILE = "/Apps/berenbaum-law/ComptaCli.xlsx"
DROPBOX_JSON = "/Apps/berenbaum-law/database.json"

